secret_token: your_secret_token
mongohq:
  database: your_db
  user: username
  password: password
pusher:
  app_id: your_app_id
  api_key: your_api_key
  api_secret: your_api_secret
chick_timers:
  food:   10s
  toilet: 20s
  fun:    1m
  milk:  2m
game_actions:
  feed:
    food: 2
  clean:
    toilet: 2
  play:
    food: -1
    toilet: -1
    fun: 2
  deliver_milk:
    food: -1
    toilet: -1
    fun: -1
    milk: 1