secret_token: your_secret_token
pusher:
  app_id: your_app_id
  api_key: your_api_key
  api_secret: your_api_secret
chick_timers:
  food:   1m
  toilet: 2m
  fun:    3m
  milk:  5m
game_actions:
  feed:
    food: 2
  clean:
    toilet: 2
  play:
    food: -1
    toilet: -1
    fun: 2
  deliver_milk:
    food: -1
    toilet: -1
    fun: -1
    milk: 1